language: node_js
node_js:
- node
- '8'
before_install:
- npm i -g firebase-tools
script:
- npm run lint
- npm run unit
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "ObzJkqUXmpdwQgSU4HV6R/QU2BxpIDTYOcUTDTKB0hDteWcFumLMs1Vzsz9NECqDvfsGyLYHkPuHxrd0gcwRpAk7b5FYm//ERB/2887gHaTu54Y75dRHUFrkpf6Qze1+gMAHHvUBKkkn9QpgLYuDcr6QWBlp1f/5y2QkJ22LPyooQUIua3iNB3G2S9Gr053JyrPjEilVZlJ3FxhmN9Q44b+RzokDgAe1GURugJMF5Kqa0C44DlN5srZ2vKhNPZGeuN7eC6u93mrbn1LDEwIr8rPT7tw+NQFUA9elFfHaFZSU06UbLm9AvI++7NfHODrrtaXyrNeihI37Nd63JbxmG7TtdrDnDCmqWzRFvCRxzukmgSDSwu6ESjv5snRTOJBJicaRi4z2fyLUlv6XFzk8qVh+icRfUC9xfOwluipSJVXA1DacfuTloEEhYQ0RPju2Y9y/ODXHXlk/0VMaCONjwTMlxpDyDewVXe+kGOxxzaNxz2WxSFvV0c7e0fw5bcMZ8BZFkknIrcHzunsllubXD6lrx6upgOwefX19j3mFwvnU65GexPPiKtqcJR/ETcpA8KCtSrYWXhOYekYcOXT/JXLurwNAS2PYX3jqWAIfmyTNeH4tETmInnFCHgQmDdpMLpUOYKjcDEGeWXfrfgxUMo6ZbhSZbKD2RUo6jDyEqXY="
  email:
    secure: "oaCUtXTPXK2izHlYAWDbEcCufFQtgQUfZxtQfzQkwldvl0hmSi6TFwyll+MjFygw2d8zdYRdbhY11VJRSmcfGpEGVRuqNMjoK70LWnli/1lO9R0jGzhc7Hd5OF7oOadyfdzLoWyPEUspby7R1T9r4miVMXcd1nHAED44bxQCJNyCCfIs8TMNOGjYjoQ4aj6TNdLA+HKXVz9XZGz5UDAZw8za8CzIiz2r8IET4GgtRkIFNZRrhf4vkEbnD1Iq8xwWvfw0dSrM1dfp6khK7I7PC08EAD0ewRsG8IOZmo9ARkSPmtGhJy+77pgxOVtVeYuvpy9L19/m0+T179J0EP52q5vTV4lf3p3MlTodZMsMtZvdfCs27wOmzV6Tev4YeGGEhCasQSwgaBiFVMONhZMLJX7ObX/KMPuMpCHRx1aPq5YvVd99njPME17qfuVPH+XQ4tDAuI0wiB+zslnwbRtkl+HscEBgXZtcuT1f56jbDMbenCLdBnrc0fVL8n1KPiwJ+LsHW8Hwwg72mdmFPFyXipry6A7W6+nxy+gBuvO7XdvqIC0hMLgPErZDGc7TreWATfl3ipQC+6Pj9sXRqEPKqz7GmtykKVCN/ocUo0ZWSR93kECinKhsR4TZNpX9eZV5Jlqb5lnXEbJPzTOcThtCKV31nj45EDf/T5nYglo2d3E="
  password:
    secure: "KatTwMXwVMOxJYP2Zo5CbthCtzsFs0i+eJUaECGYvh8rpav7M65IPL1wHlFsLrULdT4VsAho4ZKpa6xt7tIQ29om6TASLYbGviynlw0UPZ88ng8M2IcMx4403zKoKPeFAot6HIZeiOXU95zpYYACz216z19+guHoq3NqqbVmbdA5ojbB3FpPD9z7Isach0ZfCp27ZIALLIpuIw1IhpVWUBJkZ3Y03WqUL1AJooiKxjXeQKVKjsGWL28QQWBnGlCHJQ1WYfVEuWyzf+Wlw0dQ1PgIzeRngiTYRAqAhhSotGrs5UF2lRGWc41CrihidZ3/r9k6r2IcW3SlVi409mdhu0RwrZMW61o+t9rz2c+gI9T4Xg8nB6pUp+XoOcyLTSHN8vi5e7yqugQ7L53fKBtzbSAQp2zMmR+pyKI2EgQ7ZxBTUEWp3VN+RhPAWhYVpqynO8CD6EmHXQIThsLLrXpW9B6mQbHu6ancuFVRXwP15LvM5p0TZrXhCfJP3JUGTxtRKPOzZ4FhBsac1JK5p7RMw0OAfjAl1/bQqCo+MoGZkyXOGTezq7BU+cZI5VncS6X5X6bVRCnfBYmxahozC1O1IzOtGQpUyM69HfbeFD0MsBmv4Lergz2uz9QSqYwViFlqetoHwQe+G2U8ke8gofCMil9+hsi/KMVVRF12Fyj1S4U="



